-- ========================================
-- 회원 관리 DDL
-- ========================================

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 회원 테이블
CREATE TABLE MEMBER (
    MEMBER_ID               NUMBER(19)      NOT NULL,
    LOGIN_ID                VARCHAR2(50)    NOT NULL,
    EMAIL                   VARCHAR2(100)   NOT NULL,
    PASSWORD                VARCHAR2(100)   NOT NULL,
    ROLE                    VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    ACCOUNT_NON_EXPIRED     CHAR(1)         DEFAULT 'Y' NOT NULL,
    ACCOUNT_NON_LOCKED      CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREDENTIALS_NON_EXPIRED CHAR(1)         DEFAULT 'Y' NOT NULL,
    ENABLED                 CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_MEMBER_ACCOUNT_NON_EXPIRED CHECK (ACCOUNT_NON_EXPIRED IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_ACCOUNT_NON_LOCKED CHECK (ACCOUNT_NON_LOCKED IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_CREDENTIALS_NON_EXPIRED CHECK (CREDENTIALS_NON_EXPIRED IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_ENABLED CHECK (ENABLED IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_ROLE CHECK (ROLE IN ('USER', 'ADMIN', 'GUEST'))
);

-- 코멘트
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 ID (PK)';
COMMENT ON COLUMN MEMBER.LOGIN_ID IS '로그인 ID';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호 (BCrypt)';
COMMENT ON COLUMN MEMBER.ROLE IS '권한 (USER, ADMIN, GUEST)';
